### ISSUE TITLE
Sensor V2.2 compatibility

### ISSUE THREAD

**Issue by Elektroarzt** [Inqbus/somose#2]
I just bought 2 sensors and had to face that your driver is for V1.1 of the sensor but I got V2.2. Do you know if the driver is compatible to the new hardware?

**Comment by volkerjaenisch** [comment]
I got recently notice from the hardware developer. They should be 100% compatible.
I also had this confirmed by a user of the V2.2 variant. 
I will get a V2.2 in the next days and will test for my self. If positive I will adjust the GH page to include V2.2  officially as well.
Cheers,
Volker

**Comment by Elektroarzt** [comment]
Thanks for this super speedy answer.
Best regards, Thomas
